
data_path:
  train: /home/ubuntu1804/pytorch_sequence_classification/dataset/final.xlsx
  eval: /home/ubuntu1804/pytorch_sequence_classification/dataset/eval_data/eval.xlsx

tokenized_path:
  vocab2index_json_path: /home/ubuntu1804/pytorch_sequence_classification/dataset/vocab2index.json
  label2index_json_path: /home/ubuntu1804/pytorch_sequence_classification/dataset/label2index.json


