path:
  electra_path: /home/ubuntu1804/bert模型/chinese-electra-180g-small-discriminator
  preprocess_config_path: /home/ubuntu1804/pytorch_sequence_classification/dataset/preprocess_config.yaml
bert_hiddensize: 256
dense: 512
label_nums: 188
dropout: 0.8