path:
  bert_path: /Users/yangyu/bert模型/bert-base-chinese
  preprocess_config_path: /Users/yangyu/PycharmProjects/infer_of_intent/dataset/preprocess_config.yaml
bert_hiddensize: 768
dense: 512
label_nums: 188
dropout: 0.8